/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author satya
 */
public class Mframe extends javax.swing.JFrame {

    /**
     * Creates new form Mframe
     */
    public Mframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tO = new javax.swing.JTextField();
        tI = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        bCopy = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        bPM = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bCE = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        bPt = new javax.swing.JButton();
        bC = new javax.swing.JButton();
        bP = new javax.swing.JButton();
        bPr = new javax.swing.JButton();
        bBS = new javax.swing.JButton();
        bM = new javax.swing.JButton();
        bEq = new javax.swing.JButton();
        bSq = new javax.swing.JButton();
        bSqrt = new javax.swing.JButton();
        bR = new javax.swing.JButton();
        bD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULATOR");
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        tO.setEditable(false);
        tO.setBackground(new java.awt.Color(204, 204, 204));
        tO.setFont(new java.awt.Font("Trebuchet MS", 0, 25)); // NOI18N
        tO.setForeground(new java.awt.Color(51, 51, 51));
        tO.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tO.setToolTipText("Ouput Bar");

        tI.setEditable(false);
        tI.setBackground(new java.awt.Color(204, 204, 204));
        tI.setFont(new java.awt.Font("Trebuchet MS", 0, 25)); // NOI18N
        tI.setForeground(new java.awt.Color(51, 51, 51));
        tI.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tI.setText("0");
        tI.setToolTipText("Input Bar");

        bCopy.setBackground(new java.awt.Color(204, 204, 204));
        bCopy.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bCopy.setText("↓");
        bCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCopyActionPerformed(evt);
            }
        });

        b7.setBackground(new java.awt.Color(204, 204, 204));
        b7.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(204, 204, 204));
        b4.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b1.setBackground(new java.awt.Color(204, 204, 204));
        b1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        bPM.setBackground(new java.awt.Color(204, 204, 204));
        bPM.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        bPM.setText("±");
        bPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPMActionPerformed(evt);
            }
        });

        b8.setBackground(new java.awt.Color(204, 204, 204));
        b8.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b5.setBackground(new java.awt.Color(204, 204, 204));
        b5.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(204, 204, 204));
        b2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b0.setBackground(new java.awt.Color(204, 204, 204));
        b0.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        bCE.setBackground(new java.awt.Color(204, 204, 204));
        bCE.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        bCE.setText("CE");
        bCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCEActionPerformed(evt);
            }
        });

        b9.setBackground(new java.awt.Color(204, 204, 204));
        b9.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(204, 204, 204));
        b3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(204, 204, 204));
        b6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        bPt.setBackground(new java.awt.Color(204, 204, 204));
        bPt.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        bPt.setText(".");
        bPt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPtActionPerformed(evt);
            }
        });

        bC.setBackground(new java.awt.Color(204, 204, 204));
        bC.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        bC.setText("C");
        bC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCActionPerformed(evt);
            }
        });

        bP.setBackground(new java.awt.Color(204, 204, 204));
        bP.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        bP.setText("+");
        bP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPActionPerformed(evt);
            }
        });

        bPr.setBackground(new java.awt.Color(204, 204, 204));
        bPr.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        bPr.setText("x");
        bPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrActionPerformed(evt);
            }
        });

        bBS.setBackground(new java.awt.Color(204, 204, 204));
        bBS.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bBS.setText("←");
        bBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBSActionPerformed(evt);
            }
        });

        bM.setBackground(new java.awt.Color(204, 204, 204));
        bM.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        bM.setText("-");
        bM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMActionPerformed(evt);
            }
        });

        bEq.setBackground(new java.awt.Color(204, 204, 204));
        bEq.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        bEq.setText("=");
        bEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEqActionPerformed(evt);
            }
        });

        bSq.setBackground(new java.awt.Color(204, 204, 204));
        bSq.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        bSq.setText("x²");
        bSq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSqActionPerformed(evt);
            }
        });

        bSqrt.setBackground(new java.awt.Color(204, 204, 204));
        bSqrt.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        bSqrt.setText("²√x");
        bSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSqrtActionPerformed(evt);
            }
        });

        bR.setBackground(new java.awt.Color(204, 204, 204));
        bR.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        bR.setText("1/x");
        bR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRActionPerformed(evt);
            }
        });

        bD.setBackground(new java.awt.Color(204, 204, 204));
        bD.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        bD.setText("÷");
        bD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tI)
                    .addComponent(tO, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(b1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bCopy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bPM, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bCE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(b5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bBS, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bPt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bEq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bPr, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tI, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSq, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPr, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bM, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bP, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPM, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEq, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
    //9 button code
    String s=tI.getText();
    long l=s.length();
    int as=0;
    for(int i=0;i<l;i++)
    {char ch=s.charAt(i);
     if(ch=='.'||ch=='*'||ch=='/'||ch=='+'||ch=='-')
     as++;    
    }
    if(as==0)      
    {double sq=Double.parseDouble(tI.getText());
        if(sq==0)
        {tI.setText("");}}
    
    tI.setText(tI.getText()+9);
    }//GEN-LAST:event_b9ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
    //7 button code
    String s=tI.getText();
    long l=s.length();
    int as=0;
    for(int i=0;i<l;i++)
    {char ch=s.charAt(i);
     if(ch=='.'||ch=='*'||ch=='/'||ch=='+'||ch=='-')
     as++;    
    }
    if(as==0)      
    {double sq=Double.parseDouble(tI.getText());
        if(sq==0)
        {tI.setText("");}}
    
    tI.setText(tI.getText()+7);
    }//GEN-LAST:event_b7ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
    //1 button code
    String s=tI.getText();
    long l=s.length();
    int as=0;
    for(int i=0;i<l;i++)
    {char ch=s.charAt(i);
     if(ch=='.'||ch=='*'||ch=='/'||ch=='+'||ch=='-')
     as++;    
    }
    if(as==0)      
    {double sq=Double.parseDouble(tI.getText());
        if(sq==0)
        {tI.setText("");}}
    
    tI.setText(tI.getText()+1);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
    //2 button code
    String s=tI.getText();
    long l=s.length();
    int as=0;
    for(int i=0;i<l;i++)
    {char ch=s.charAt(i);
     if(ch=='.'||ch=='*'||ch=='/'||ch=='+'||ch=='-')
     as++;    
    }
    if(as==0)      
    {double sq=Double.parseDouble(tI.getText());
        if(sq==0)
        {tI.setText("");}}
    
    tI.setText(tI.getText()+2);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
    //3 button code
    String s=tI.getText();
    long l=s.length();
    int as=0;
    for(int i=0;i<l;i++)
    {char ch=s.charAt(i);
     if(ch=='.'||ch=='*'||ch=='/'||ch=='+'||ch=='-')
     as++;    
    }
    if(as==0)      
    {double sq=Double.parseDouble(tI.getText());
        if(sq==0)
        {tI.setText("");}}
    
    tI.setText(tI.getText()+3);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
    //4 button code
    String s=tI.getText();
    long l=s.length();
    int as=0;
    for(int i=0;i<l;i++)
    {char ch=s.charAt(i);
     if(ch=='.'||ch=='*'||ch=='/'||ch=='+'||ch=='-')
     as++;    
    }
    if(as==0)      
    {double sq=Double.parseDouble(tI.getText());
        if(sq==0)
        {tI.setText("");}}
    
    tI.setText(tI.getText()+4);
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
    //5 button code
    String s=tI.getText();
    long l=s.length();
    int as=0;
    for(int i=0;i<l;i++)
    {char ch=s.charAt(i);
     if(ch=='.'||ch=='*'||ch=='/'||ch=='+'||ch=='-')
     as++;    
    }
    if(as==0)      
    {double sq=Double.parseDouble(tI.getText());
        if(sq==0)
        {tI.setText("");}}
    
    tI.setText(tI.getText()+5);
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
    //6 button code
    String s=tI.getText();
    long l=s.length();
    int as=0;
    for(int i=0;i<l;i++)
    {char ch=s.charAt(i);
     if(ch=='.'||ch=='*'||ch=='/'||ch=='+'||ch=='-')
     as++;    
    }
    if(as==0)      
    {double sq=Double.parseDouble(tI.getText());
        if(sq==0)
        {tI.setText("");}}
    
    tI.setText(tI.getText()+6);
    }//GEN-LAST:event_b6ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
    //8 button code
    String s=tI.getText();
    long l=s.length();
    int as=0;
    for(int i=0;i<l;i++)
    {char ch=s.charAt(i);
     if(ch=='.'||ch=='*'||ch=='/'||ch=='+'||ch=='-')
     as++;    
    }
    if(as==0)      
    {double sq=Double.parseDouble(tI.getText());
        if(sq==0)
        {tI.setText("");}}
    
    tI.setText(tI.getText()+8);
    }//GEN-LAST:event_b8ActionPerformed

    private void bPtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPtActionPerformed
    //decimal button code
    String s=tI.getText(),s1="";
    int l=s.length();
    int as=0,ad=0,af=0;
    for(int i=0;i<l;i++)
    {
     char ch=s.charAt(i);
     if(ch=='*'||ch=='/'||ch=='+'||ch=='-')
     {
      as++;
      s1=s.substring(i+1,l);
     }
     if(ch=='.')
     ad++;
    }
    if(as==0&&ad==0)
    tI.setText(tI.getText()+'.');
    else
    {
      int l1=s1.length();
      for(int i=0;i<l1;i++)
      {
       char ch=s1.charAt(i);
       if(ch=='.')
       af++;    
      }
      if(af==0&&l1>0)
      tI.setText(tI.getText()+'.');
    }
    }//GEN-LAST:event_bPtActionPerformed

    private void bRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRActionPerformed
    //Reciprocal button code
    String s=tI.getText(); 
    String st=s;
    int l=s.length(); 
    String s1="";
    String s2="";
    int as=0,ad=0,af=0; 
    char ch1=' ';
    double qq=0;
    char ch2=s.charAt(0);
    if(ch2=='-')
    {
     s=s.substring(1);
     l=s.length();
     af++;
     tI.setText(s);
    }
    for(int i=0;i<l;i++)
    {
     char ch=s.charAt(i);
     if(ch=='+'||ch=='-'||ch=='/'||ch=='*')
     {
      as++;
     }
    }
    char chp=s.charAt(l-1);
    if(chp=='.' || chp=='-' || chp=='+' || chp=='/' || chp=='*')
    {
     ad++;
    }
  
     if((as>0)&&(ad==0))
     {
      for(int i=0;i<l;i++)
      {
       char ch=s.charAt(i);
       if(ch=='+'||ch=='-'||ch=='/'||ch=='*')
       {
        s1=s.substring(0,i);
        s2=s.substring(i+1);
        ch1=ch;
       }
      }
      if(ch1=='+')
      { 
       qq=Double.parseDouble(s1)+Double.parseDouble(s2);
       tI.setText(qq+""); 
      }
      if(ch1=='-')
      { 
       qq=Double.parseDouble(s1)-Double.parseDouble(s2);
       tI.setText(qq+""); 
      }
      if(ch1=='/')
      { 
       qq=Double.parseDouble(s1)/Double.parseDouble(s2);  
       tI.setText(qq+""); 
      }
      if(ch1=='*')
      { 
       qq=Double.parseDouble(s1)*Double.parseDouble(s2);  
       tI.setText(qq+""); 
      }
     }
    if(ad==0)
    {
     double d=Double.parseDouble(tI.getText());
     if(af>0)
     {
      d=0-d;
     }
     d=1/d;
     tO.setText(d+"");
    }
    else
    {
     tO.setText("Error");
     tI.setText(st);
    }
    }//GEN-LAST:event_bRActionPerformed

    private void bCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCActionPerformed
    //clear input and output screen button code
    tI.setText("0");
    tO.setText("");
    }//GEN-LAST:event_bCActionPerformed

    private void bCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCEActionPerformed
    //Clear Input screen button code
    tI.setText("0");
    }//GEN-LAST:event_bCEActionPerformed

    private void bSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSqrtActionPerformed
    //Square root button code
    String s=tI.getText(); 
    String st=s;
    int l=s.length(); 
    String s1="";
    String s2="";
    int as=0,ad=0,af=0; 
    char ch1=' ';
    double qq=0;
    char ch2=s.charAt(0);
    if(ch2=='-')
    {
     s=s.substring(1);
     l=s.length();
     af++;
     tI.setText(s);
    }
    for(int i=0;i<l;i++)
    {
     char ch=s.charAt(i);
     if(ch=='+'||ch=='-'||ch=='/'||ch=='*')
     {
      as++;
     }
    }
    char chp=s.charAt(l-1);
    if(chp=='.' || chp=='-' || chp=='+' || chp=='/' || chp=='*')
    {
     ad++;
    }
  
     if((as>0)&&(ad==0))
     {
      for(int i=0;i<l;i++)
      {
       char ch=s.charAt(i);
       if(ch=='+'||ch=='-'||ch=='/'||ch=='*')
       {
        s1=s.substring(0,i);
        s2=s.substring(i+1);
        ch1=ch;
       }
      }
      if(ch1=='+')
      { 
       qq=Double.parseDouble(s1)+Double.parseDouble(s2);
       tI.setText(qq+""); 
      }
      if(ch1=='-')
      { 
       qq=Double.parseDouble(s1)-Double.parseDouble(s2);
       tI.setText(qq+""); 
      }
      if(ch1=='/')
      { 
       qq=Double.parseDouble(s1)/Double.parseDouble(s2);  
       tI.setText(qq+""); 
      }
      if(ch1=='*')
      { 
       qq=Double.parseDouble(s1)*Double.parseDouble(s2);  
       tI.setText(qq+""); 
      }
     }
    if(ad==0)
    {
     double d=Double.parseDouble(tI.getText());
     if(af>0)
     {
      d=0-d;
     }
     d=Math.sqrt(d);
     tO.setText(d+"");
    }
    else
    {
     tO.setText("Error");
     tI.setText(st);
    }
    }//GEN-LAST:event_bSqrtActionPerformed

    private void bPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPMActionPerformed
    //Sign changing button coding
    String s=tI.getText(); 
    String st=s;
    int l=s.length(); 
    String s1="";
    String s2="";
    int as=0,ad=0,af=0; 
    char ch1=' ';
    double qq=0;
    char ch2=s.charAt(0);
    if(ch2=='-')
    {
     s=s.substring(1);
     l=s.length();
     af++;
     tI.setText(s);
    }
    for(int i=0;i<l;i++)
    {
     char ch=s.charAt(i);
     if(ch=='+'||ch=='-'||ch=='/'||ch=='*')
     {
      as++;
     }
    }
    char chp=s.charAt(l-1);
    if(chp=='.' || chp=='-' || chp=='+' || chp=='/' || chp=='*')
    {
     ad++;
    }
  
     if((as>0)&&(ad==0))
     {
      for(int i=0;i<l;i++)
      {
       char ch=s.charAt(i);
       if(ch=='+'||ch=='-'||ch=='/'||ch=='*')
       {
        s1=s.substring(0,i);
        s2=s.substring(i+1);
        ch1=ch;
       }
      }
      if(ch1=='+')
      { 
       qq=Double.parseDouble(s1)+Double.parseDouble(s2);
       tI.setText(qq+"");
       tO.setText(qq+"");
      }
      if(ch1=='-')
      { 
       qq=Double.parseDouble(s1)-Double.parseDouble(s2);
       tI.setText(qq+"");
       tO.setText(qq+"");
      }
      if(ch1=='/')
      { 
       qq=Double.parseDouble(s1)/Double.parseDouble(s2);  
       tI.setText(qq+"");
       tO.setText(qq+"");
      }
      if(ch1=='*')
      { 
       qq=Double.parseDouble(s1)*Double.parseDouble(s2);  
       tI.setText(qq+"");
       tO.setText(qq+"");
      }
     }
    if(ad==0)
    {
     double d=Double.parseDouble(tI.getText());
     if(af>0)
     {
      d=0-d;
     }
     if(d>0)
     {
      d=0-d;
     }
     else
     {
      d=Math.abs(d);
     }
     tI.setText(d+"");
    }
    else
    {
     tO.setText("Error");
     tI.setText(st);
    }
    }//GEN-LAST:event_bPMActionPerformed

    private void bPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrActionPerformed
    //Multiply button code
    String s=tI.getText();
    String s1="";
    String s2="";
    int as=0,ad=0; 
    char ch1=' ';
    double qq=0;
    int l=s.length();
    char ch2=s.charAt(0);
    if(ch2=='-')
    {
     s=s.substring(1);
     l=s.length();
     ad++;
    }
    for(int i=0;i<l;i++)
    {
     char ch=s.charAt(i);
     if(ch=='*'||ch=='/'||ch=='+'||ch=='-')
     as++;    
    }
    if(as==0 && s.charAt(l-1)!='.')
    {
     tI.setText(tI.getText()+'*');
    }
    char chp=s.charAt(l-1);
    if(chp=='*' || chp=='/' || chp=='+' || chp=='-')
    {
     String sp="";
     for(int i=0;i<(l-1);i++)
     {
      char ch=s.charAt(i);
      sp=sp+ch;   
     }
     sp=sp+"*";
     tI.setText(sp);   
    }
    if(chp!='*' && chp!='/' && chp!='+' && chp!='-' && chp!='.')
    {
    if(as>0)    
    
    {
     for(int i=0;i<l;i++)
     {
      char ch=s.charAt(i);
      if(ch=='+'||ch=='-'||ch=='/'||ch=='*')
      {
       s1=s.substring(0,i);
       s2=s.substring(i+1);
       ch1=ch;
      }
     } 
     if(ch1=='+')
     {
      qq=Double.parseDouble(s1)+Double.parseDouble(s2);
     }
     if(ch1=='-')
     {
      qq=Double.parseDouble(s1)-Double.parseDouble(s2);
     }
     if(ch1=='/')
     {
      qq=Double.parseDouble(s1)/Double.parseDouble(s2);  
     }
     if(ch1=='*')
     {
      qq=Double.parseDouble(s1)*Double.parseDouble(s2); 
     }
     if(ad>0)
     {
      qq=0-qq;   
     }
     tI.setText(qq+"*"); 
     tO.setText(qq+"");
    }
    }
    }//GEN-LAST:event_bPrActionPerformed

    private void bPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPActionPerformed
    //plus button code
    String s=tI.getText();
    String s1="";
    String s2="";
    int as=0,ad=0; 
    char ch1=' ';
    double qq=0;
    int l=s.length();
    char ch2=s.charAt(0);
    if(ch2=='-')
    {
     s=s.substring(1);
     l=s.length();
     ad++;
    }
    for(int i=0;i<l;i++)
    {
     char ch=s.charAt(i);
     if(ch=='*'||ch=='/'||ch=='+'||ch=='-')
     as++;    
    }
    if(as==0 && s.charAt(l-1)!='.')
    {
     tI.setText(tI.getText()+'+');
    }
    char chp=s.charAt(l-1);
    if(chp=='*' || chp=='/' || chp=='+' || chp=='-')
    {
     String sp="";
     for(int i=0;i<(l-1);i++)
     {
      char ch=s.charAt(i);
      sp=sp+ch;   
     }
     sp=sp+"+";
     tI.setText(sp);   
    }
    if(chp!='*' && chp!='/' && chp!='+' && chp!='-' && chp!='.')
    {
    if(as>0)    
    
    {
     for(int i=0;i<l;i++)
     {
      char ch=s.charAt(i);
      if(ch=='+'||ch=='-'||ch=='/'||ch=='*')
      {
       s1=s.substring(0,i);
       s2=s.substring(i+1);
       ch1=ch;
      }
     } 
     if(ch1=='+')
     {
      qq=Double.parseDouble(s1)+Double.parseDouble(s2);
     }
     if(ch1=='-')
     {
      qq=Double.parseDouble(s1)-Double.parseDouble(s2);
     }
     if(ch1=='/')
     {
      qq=Double.parseDouble(s1)/Double.parseDouble(s2);  
     }
     if(ch1=='*')
     {
      qq=Double.parseDouble(s1)*Double.parseDouble(s2); 
     }
     if(ad>0)
     {
      qq=0-qq;   
     }
     tI.setText(qq+"+"); 
     tO.setText(qq+"");
    }
    }
    }//GEN-LAST:event_bPActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
    //0 button code
    String s=tI.getText();
    long l=s.length();
    int as=0;
    for(int i=0;i<l;i++)
    {char ch=s.charAt(i);
     if(ch=='.'||ch=='*'||ch=='/'||ch=='+'||ch=='-')
     as++;    
    }
    if(as==0)      
    {double sq=Double.parseDouble(tI.getText());
        if(sq==0)
        {tI.setText("");}}
    
    tI.setText(tI.getText()+0);
    }//GEN-LAST:event_b0ActionPerformed

    private void bDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDActionPerformed
    //Divide button code
    String s=tI.getText();
    String s1="";
    String s2="";
    int as=0,ad=0; 
    char ch1=' ';
    double qq=0;
    int l=s.length();
    char ch2=s.charAt(0);
    if(ch2=='-')
    {
     s=s.substring(1);
     l=s.length();
     ad++;
    }
    for(int i=0;i<l;i++)
    {
     char ch=s.charAt(i);
     if(ch=='*'||ch=='/'||ch=='+'||ch=='-')
     as++;    
    }
    if(as==0 && s.charAt(l-1)!='.')
    {
     tI.setText(tI.getText()+'/');
    }
    char chp=s.charAt(l-1);
    if(chp=='*' || chp=='/' || chp=='+' || chp=='-')
    {
     String sp="";
     for(int i=0;i<(l-1);i++)
     {
      char ch=s.charAt(i);
      sp=sp+ch;   
     }
     sp=sp+"/";
     tI.setText(sp);   
    }
    if(chp!='*' && chp!='/' && chp!='+' && chp!='-' && chp!='.')
    {
    if(as>0)    
    
    {
     for(int i=0;i<l;i++)
     {
      char ch=s.charAt(i);
      if(ch=='+'||ch=='-'||ch=='/'||ch=='*')
      {
       s1=s.substring(0,i);
       s2=s.substring(i+1);
       ch1=ch;
      }
     } 
     if(ch1=='+')
     {
      qq=Double.parseDouble(s1)+Double.parseDouble(s2);
     }
     if(ch1=='-')
     {
      qq=Double.parseDouble(s1)-Double.parseDouble(s2);
     }
     if(ch1=='/')
     {
      qq=Double.parseDouble(s1)/Double.parseDouble(s2);  
     }
     if(ch1=='*')
     {
      qq=Double.parseDouble(s1)*Double.parseDouble(s2); 
     }
     if(ad>0)
     {
      qq=0-qq;   
     }
     tI.setText(qq+"/"); 
     tO.setText(qq+"");
    }
    }
    
    }//GEN-LAST:event_bDActionPerformed

    private void bMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMActionPerformed
    //minus button code
    String s=tI.getText();
    String s1="";
    String s2="";
    int as=0,ad=0; 
    char ch1=' ';
    double qq=0;
    int l=s.length();
    char ch2=s.charAt(0);
    if(ch2=='-')
    {
     s=s.substring(1);
     l=s.length();
     ad++;
    }
    for(int i=0;i<l;i++)
    {
     char ch=s.charAt(i);
     if(ch=='*'||ch=='/'||ch=='+'||ch=='-')
     as++;    
    }
    if(as==0 && s.charAt(l-1)!='.')
    {
     tI.setText(tI.getText()+'-');
    }
    char chp=s.charAt(l-1);
    if(chp=='*' || chp=='/' || chp=='+' || chp=='-')
    {
     String sp="";
     for(int i=0;i<(l-1);i++)
     {
      char ch=s.charAt(i);
      sp=sp+ch;   
     }
     sp=sp+"-";
     tI.setText(sp);   
    }
    if(chp!='*' && chp!='/' && chp!='+' && chp!='-' && chp!='.')
    {
    if(as>0)    
    
    {
     for(int i=0;i<l;i++)
     {
      char ch=s.charAt(i);
      if(ch=='+'||ch=='-'||ch=='/'||ch=='*')
      {
       s1=s.substring(0,i);
       s2=s.substring(i+1);
       ch1=ch;
      }
     } 
     if(ch1=='+')
     {
      qq=Double.parseDouble(s1)+Double.parseDouble(s2);
     }
     if(ch1=='-')
     {
      qq=Double.parseDouble(s1)-Double.parseDouble(s2);
     }
     if(ch1=='/')
     {
      qq=Double.parseDouble(s1)/Double.parseDouble(s2);  
     }
     if(ch1=='*')
     {
      qq=Double.parseDouble(s1)*Double.parseDouble(s2); 
     }
     if(ad>0)
     {
      qq=0-qq;   
     }
     tI.setText(qq+"-"); 
     tO.setText(qq+"");
    }
    }
    }//GEN-LAST:event_bMActionPerformed

    private void bSqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSqActionPerformed
    //Square button code
    String s=tI.getText(); 
    String st=s;
    int l=s.length(); 
    String s1="";
    String s2="";
    int as=0,ad=0,af=0; 
    char ch1=' ';
    double qq=0;
    char ch2=s.charAt(0);
    if(ch2=='-')
    {
     s=s.substring(1);
     l=s.length();
     af++;
     tI.setText(s);
    }
    for(int i=0;i<l;i++)
    {
     char ch=s.charAt(i);
     if(ch=='+'||ch=='-'||ch=='/'||ch=='*')
     {
      as++;
     }
    }
    char chp=s.charAt(l-1);
    if(chp=='.' || chp=='-' || chp=='+' || chp=='/' || chp=='*')
    {
     ad++;
    }
  
     if((as>0)&&(ad==0))
     {
      for(int i=0;i<l;i++)
      {
       char ch=s.charAt(i);
       if(ch=='+'||ch=='-'||ch=='/'||ch=='*')
       {
        s1=s.substring(0,i);
        s2=s.substring(i+1);
        ch1=ch;
       }
      }
      if(ch1=='+')
      { 
       qq=Double.parseDouble(s1)+Double.parseDouble(s2);
       tI.setText(qq+""); 
      }
      if(ch1=='-')
      { 
       qq=Double.parseDouble(s1)-Double.parseDouble(s2);
       tI.setText(qq+""); 
      }
      if(ch1=='/')
      { 
       qq=Double.parseDouble(s1)/Double.parseDouble(s2);  
       tI.setText(qq+""); 
      }
      if(ch1=='*')
      { 
       qq=Double.parseDouble(s1)*Double.parseDouble(s2);  
       tI.setText(qq+""); 
      }
     }
    if(ad==0)
    {
     double d=Double.parseDouble(tI.getText());
     if(af>0)
     {
      d=0-d;
     }
     d=d*d;
     tO.setText(d+"");
    }
    else
    {
     tO.setText("Error");
     tI.setText(st);
    }
    }//GEN-LAST:event_bSqActionPerformed

    private void bCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCopyActionPerformed
    //Copy Result Button Code
    String sO=tO.getText();
    long l=sO.length();
    if(l>0)
    {
     tI.setText(sO);
     tO.setText("");
    }
    }//GEN-LAST:event_bCopyActionPerformed

    private void bBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBSActionPerformed
    //Backspace button code
    String s=tI.getText();
    long l=s.length();
     String s1="";
     for(int i=0;i<(l-1);i++)
     {
      char ch=s.charAt(i);
      s1=s1+ch;   
     }
     tI.setText(s1);
    if(l==1)
    tI.setText("0");   
   
    }//GEN-LAST:event_bBSActionPerformed

    private void bEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEqActionPerformed
    //equals to button code
    String s=tI.getText();
    String s1="";
    String s2="";
    int as=0,ad=0; 
    char ch1=' ';
    double qq=0,out=0;
    int l=s.length();
    char ch2=s.charAt(0);
    if(ch2=='-')
    {
     s=s.substring(1);
     l=s.length();
     ad++;
    }
    for(int i=0;i<l;i++)
    {
     char ch=s.charAt(i);
     if(ch=='*'||ch=='/'||ch=='+'||ch=='-')
     as++;    
    }
    char chp=s.charAt(l-1);
    if(chp=='*' || chp=='/' || chp=='+' || chp=='-')
    {
     tO.setText("Error");
    }
    if(chp!='*' && chp!='/' && chp!='+' && chp!='-' && chp!='.')
    {
    if(as==0)
    {
     out=Double.parseDouble(s);   
    }
    if(as>0)    
    
    {
     for(int i=0;i<l;i++)
     {
      char ch=s.charAt(i);
      if(ch=='+'||ch=='-'||ch=='/'||ch=='*')
      {
       s1=s.substring(0,i);
       s2=s.substring(i+1);
       ch1=ch;
      }
     } 
     if(ch1=='+')
     {
      qq=Double.parseDouble(s1)+Double.parseDouble(s2);
     }
     if(ch1=='-')
     {
      qq=Double.parseDouble(s1)-Double.parseDouble(s2);
     }
     if(ch1=='/')
     {
      qq=Double.parseDouble(s1)/Double.parseDouble(s2);  
     }
     if(ch1=='*')
     {
      qq=Double.parseDouble(s1)*Double.parseDouble(s2); 
     } 
     out=qq;
     if(ad>0)
    {
     out=0-out;   
    }
    tO.setText(out+"");
    }
    }
    
    }//GEN-LAST:event_bEqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bBS;
    private javax.swing.JButton bC;
    private javax.swing.JButton bCE;
    private javax.swing.JButton bCopy;
    private javax.swing.JButton bD;
    private javax.swing.JButton bEq;
    private javax.swing.JButton bM;
    private javax.swing.JButton bP;
    private javax.swing.JButton bPM;
    private javax.swing.JButton bPr;
    private javax.swing.JButton bPt;
    private javax.swing.JButton bR;
    private javax.swing.JButton bSq;
    private javax.swing.JButton bSqrt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField tI;
    private javax.swing.JTextField tO;
    // End of variables declaration//GEN-END:variables
}
